version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file: .env
    
  frontend:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
